name: Deploy NestJS to cPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build NestJS application
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload build artifacts to cPanel
        uses: lishuping/ftp-action@v4

        with:
          server: cpanel.example.com
          username: cpanel_username
          password: cpanel_password
          remote_directory: /public_html

      - name: Set file permissions
        run: ssh -i ~/.ssh/<ssh_key_file> cpanel_username@cpanel.example.com "chmod -R 755 /public_html"

      - name: Restart Apache
        run: ssh -i ~/.ssh/<ssh_key_file> cpanel_username@cpanel.example.com "/usr/local/apache2/bin/apachectl restart"
