name: Deploy NestJS to Heroku
on:
  push:
    branches:
      - backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build NestJS application
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: e5456e5d-5dc2-4428-94ab-282c6bb6112c
          heroku_app_name: chikiet88@gmail.com
          heroku_email: "@Hikiet88"
          remote_branch: master
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Set Heroku API key
    #     run: echo "$e5456e5d-5dc2-4428-94ab-282c6bb6112c" | gh secret set e5456e5d-5dc2-4428-94ab-282c6bb6112c
    #   - name: Deploy to Heroku
    #     run: heroku deploy
