name: Deploy NestJS to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build NestJS application
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Heroku API key
        run: echo "$e5456e5d-5dc2-4428-94ab-282c6bb6112c" | gh secret set e5456e5d-5dc2-4428-94ab-282c6bb6112c
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4
        with:
          heroku_api_key: e5456e5d-5dc2-4428-94ab-282c6bb6112c
          heroku_app_name: my-nestjs-app
